#! /usr/bin/bash

my_dir="$(dirname "$0")"

test_function()
{
  current_status=$1
  current_battery=$2

  if [[ $current_status -eq 0 && $current_battery -lt 61 ]] || [[ $current_status -eq 1 && $current_battery -gt 90 ]]
  then
    "$my_dir/battery-alert"
    if [ $? -eq 0 ]; then
     echo PASS
    else
     echo FAIL
    fi
  fi

  if [[ $current_status -eq 0 && $current_battery -ge 10 ]] || [[ $current_status -eq 1 && $current_battery -le 90 ]]
  then
    # do something to return exit status
    # idk how to do and what to do right now, any ideas?
    if [ $? -eq 0 ]; then
     echo PASS
    else
     echo FAIL
    fi
  fi
}

test_function 0 0
test_function 0 5
test_function 0 10
test_function 0 50
test_function 1 90
test_function 1 95
test_function 1 100
